sudo : required
services:
        - docker

before_install:
        - docker build -t sumit/docker-react  -f Dockerfile.dev .

script:
        - docker run -e CI=true  sumit/docker-react npm run test -- --coverage

deploy:
        provider: elasticbeanstalk
        region: "ap-south-1"
        app: "docker-react"
        env: "Dockerreact-env"
        bucket_name: "elasticbeanstalk-ap-south-1-936865951761"
        bucket_path: "docker-react"
        on:
                branch: main
        access_key_id: "$AWS_ACCESS_KEY"
        secret_access_key:
                secure: "$AWS_SECRET_KEY"

