sudo : required
services:
        - docker

before_install:
        - docker build -t sumit/docker-react  -f Dockerfile.dev .

script:
        - docker run sumit/docker-react npm run test -- --coverage
